<a href="https://colab.research.google.com/github/chicago007/test2/blob/main/HYCU_%EC%9D%B8%EA%B3%B5%EC%A7%80%EB%8A%A5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
a = [1, 10,20,30,40,50,10]
a.append(6)
print(a)
a.remove(1)
print(a)
del a[3]
print(a)

[1, 10, 20, 30, 40, 50, 10, 6]
[10, 20, 30, 40, 50, 10, 6]
[10, 20, 30, 50, 10, 6]


In [ ]:
a = (1, 10,20,30)
b= (40,50,10)
a=a+b
a=a*3
print(a)
print(len(a))


(1, 10, 20, 30, 40, 50, 10, 1, 10, 20, 30, 40, 50, 10, 1, 10, 20, 30, 40, 50, 10)
21


In [ ]:
a = {1: 'a'}
a[2] = 'b'
print(a) #a {1: 'a', 2: 'b'}
a[3] = [1,2,3]
print(a) #a {1: 'a', 2: 'b', 3: [1, 2, 3]}

{1: 'a', 2: 'b'}
{1: 'a', 2: 'b', 3: [1, 2, 3]}


In [ ]:
a = {'name':'hycu', 'phone':'0222901111', 'birth': '1111'}
for i in a.keys():
  print(i)
print(list(a.keys())) #['name', 'phone', 'birth']
'name' in a

name
phone
birth
['name', 'phone', 'birth']


True

In [ ]:
a = set([1,2,3])
a2= list(a)
print(a)
print(a2) #[1, 2, 3]
print(a2[0]) #1

print(type(a))

{1, 2, 3}
[1, 2, 3]
1
<class 'set'>


In [ ]:
s1 = set([1, 2, 3])
s1.update([4, 5, 6])
print(s1) #{1, 2, 3, 4, 5, 6}
s1 = set([1, 2, 3])
s1.remove(2)
print(s1) #{1, 3}


{1, 2, 3, 4, 5, 6}
{1, 3}


In [ ]:
s1 = set([1, 2, 3, 4, 5, 6])
s2 = set([4, 5, 6, 7, 8, 9])
print(s1 & s2)
print(s1.intersection(s2))
print(s1 | s2)
print(s1.union(s2))
print(s1 - s2)
print(s1.difference(s2))

{4, 5, 6}
{4, 5, 6}
{1, 2, 3, 4, 5, 6, 7, 8, 9}
{1, 2, 3, 4, 5, 6, 7, 8, 9}
{1, 2, 3}
{1, 2, 3}


In [ ]:
tmp1=[10,20,30,40,50]
print(tmp1[1:3])
tmp2=(1,2,3,4,5)
print(type(tmp2))
tmp3={'name':'kim hycu', 'dept':'sw'}
for i in tmp3:
  print(i, end=' ')
print()
for i in tmp3.values():
  print(i, end=' ')

[20, 30]
<class 'tuple'>
name dept 
kim hycu sw 

In [ ]:
def tmp4(a):
  for i in a:
    print(i, end=" ")
  print()

tmp2=(1,2,3,4,5)
print(tmp4(tmp2))


1 2 3 4 5 
None


In [ ]:
class tmp5:
  def __init__(self, n1,n2):
    self.n1=n1
    self.n2=n2

  def add(self):
    return self.n1+self.n2

tmp6=tmp5(1,2)
print(tmp6.add())

3


In [29]:
import numpy as np

i=np.array([[1,2],[3,4]])
j=np.array([[1,2]])
print(i)
print(j)
print(i+j)

[[1 2]
 [3 4]]
[[1 2]]
[[2 4]
 [4 6]]


In [30]:
import numpy as np
a=np.array([[1,2,3],[3,4,5]])
print(a.T)


[[1 3]
 [2 4]
 [3 5]]


In [31]:
import numpy as np
i=np.array([[1,2],[3,4]])
j=np.array([[1,2],[3,4]])
print(i+j)
print(i-j)
print(i*j)
print(i/j)

[[2 4]
 [6 8]]
[[0 0]
 [0 0]]
[[ 1  4]
 [ 9 16]]
[[1. 1.]
 [1. 1.]]


In [33]:
import numpy as np
# i=np.array([[1,2],[3,4]])
# j=np.array([[1,2],[3,4]])
# print(np.dot(i,j))
A = np.array([10, 20, 30, 40, 50, 60]).reshape(3, 2)
print(A)
print(A[0, 0], A[0][0])
print(A[2,1], A[2][1])
print(A[0:-1, 1:2])
print(A[:, 0])
print(A[:, :])


[[10 20]
 [30 40]
 [50 60]]
10 10
60 60
[[20]
 [40]]
[10 30 50]
[[10 20]
 [30 40]
 [50 60]]


In [35]:
import numpy as np
i=np.array([1,2,3])
print(i)
print(type(i))
j=np.array([[1,2], [3,4]])
print(j)
print(type(j))

[1 2 3]
<class 'numpy.ndarray'>
[[1 2]
 [3 4]]
<class 'numpy.ndarray'>
